### ISSUE TITLE
Erlang RLP implementation encodes 0s differently from RLP spec

### ISSUE THREAD

**Issue by randomshinichi** [aeternity/aeternity#2213]
## Expected Behavior
Serializing a transaction using unmodified RLP code from Ethereum should result in a valid transaction that the node accepts.
Specifically, `The integer 0 = [ 0x80 ]` from https://github.com/ethereum/wiki/wiki/RLP

## Actual Behavior
A 0 seems to be encoded by not having a byte there in the first place.
[This commit](https://github.com/aeternity/aepp-sdk-go/pull/7/commits/63f37d6035325edf78ad0b3263b7f7ff455c1a68) (changing the original RLP implementation) allowed aepp-sdk-go to work with the node again.

[This commit](https://github.com/aeternity/aepp-sdk-go/commit/84a4581b526ff5babc09c2623b8449fe38c18f9a) shows on the left what Ethereum RLP would have serialized, and on the right, how 0 needs to be encoded for the aeternity node to accept it.

## Steps to Reproduce the Problem

  1. Create a transaction with one field being 0.
  2. Sign it.
  3. Broadcast to a node.

## Specifications

  - Virtualization: none
  - Hardware specs:
    * RAM: 16GB
    * CPU: Ivy Bridge
  - OS: Manjaro Linux
  - Node Version: Behaviour present since at least v1.2.0

**Comment by gorillainduction** [comment]
This is an effect of a design decision in the Aeternity node to avoid some ambiguity in the RLP encoding.

The integer `0` is in https://github.com/ethereum/wiki/wiki/RLP defined as `[ 0x80 ]` but the byte array encoded integer `<< 0 >>` is defined as `[ 0x00 ]`.

When decoding `[ 0x80 ]` the algorithm would have to choose between `<<>>` and `0`, but we can avoid this problem by never encoding plain integers (except for the RLP internal size fields) in the Aeternity protocol. Integers in Aeternity serialization (including 0) is always first transformed to its byte array equivalent and then encoded.

Viewing the `[ 0x80 ]` as the encoding of either the empty byte array or the integer 0 leads to the unfortunate case of two deserializations yielding the same value, since both '[ 0x00 ]` and `[ 0x80 ]` can be deserialized as the integer 0. 

This is not obviously dangerous, but it is not obviously _not_ dangerous either.

**Comment by randomshinichi** [comment]
Great explanation, thanks. I'll update the unittests on my side then.
