### ISSUE TITLE
Core: introduce GC for state

### ISSUE THREAD

**Issue by sennui** [aeternity/aeternity#2845]
## Expected Behavior

Database of states doesn't explode

## Actual Behavior

Database of states grows really fast

## Design

To be published. 

It focuses around re-writing trees at given height to new table. The old table holding past states can be dropped.

**Comment by evdoks** [comment]
Is it implemented in PR #2897 ?

Also, do we have design published somewhere?

**Comment by ThomasArts** [comment]
**Risk analysis**

Identified risks that needs specific testing and specify the results of that testing and conclusions for mitigation
1) Could GC interfere with mining? GC activated when mining / mining possibility missed because GC-ing
2) Can we delete data we don't want to loose?
3) Can we sync with a node that is garbage collected? Do we get the same state as when we sync with a node that has not garbage collected?
4) Is there an overal performance decrease by implementing sync
