### ISSUE TITLE
FATE cannot get blockhash of current generation

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#3002]
## Expected Behavior

For Sophia contract:
```
entrypoint my_hash() =
    Chain.block_hash(Chain.block_height)
```

One expects a hash back, but instead `None` is returned.

The cause is in:
https://github.com/aeternity/aeternity/blob/afef1aa92a1cd6a75f4037d8e2be540ed4114612/apps/aefate/src/aefa_fate_op.erl#L858

There is an off-by-one error `>=` should be `>`. This is consensus breaking and has to be conditional w.r.t. next hard fork. If we change that, a request to relax 256 blocks in the past to something that reflects 24 hours or so.

Some discussion needed on how to deal with contracts that change semantics. Clearly, contracts created after the hardfork will have to respect the new semantics, but should we support different call outrcomes for contracts created before hardfork, but called after hardfork? Do we need a general policy for this or is this a case-by-case discussion?

**Comment by gorillainduction** [comment]
This is not an error, but intentional to mimic the blockhash instruction from ethereum.

That being said, I see no problem in changing it, and bump the VM version. This is nothing new, we have done this many times. Contracts are always running in the VM-version they stated on creation, so again, this is a general problem that is already solved.

**Comment by gorillainduction** [comment]
Just another comment on the current behavior.

The blockhash on the current block cannot be known in ethereum since the blockhash might reflect the outcome of the execution of the instruction. In aeternity, the blockhash is from the key block of the current generation, which is of course accessible.

The reasoning when I implemented the current behavior is that you might rely on the current height to return `None`, but with a careful announcement, this shouldn't be a problem.

**Comment by hanssv** [comment]
The new suggested behavior might be confusing to an Ethereum/Solidity developer, but it makes sense from a logical perspective... 

Since we have the block hash at `Height` we should expose it, but as @gorillainduction mentions the change should be communicated.

**Comment by ThomasArts** [comment]
@gorillainduction I'm now also curious whether there is a ration behind going only 256 blocks back in time to get the hash. The more one goes back in time, the more expensive it gets, I guess. But is 256 arbitary or with deep thoughts? I wrote a contract that needs the used to react and the blockhash is needed at the moment of reaction. That means, for 256, that the user must react within half a day. Somehow 24 hours would have seemed more reasonable. Clearly I can rewrite my contract, but I wonder whether the contract writer is in general aware of this restriction.

**Comment by hanssv** [comment]
256 is the same as Ethereum, so **we** haven't put any deep thought into this... Keeping more key-block headers around doesn't sound infeasible to me 🤔 But making the cost depend on how far in the past it is probably isn't a bad idea ;-)

**Comment by gorillainduction** [comment]
@hanssv is correct of course ;-) Not much thought went into this.

Just remember that the historical distance puts a minimum demand on how much a validating node needs to remember the block hashes. It is true that the full chain doesn't need to be around for this, though, so it might not be a problem.

However, it would be good to find a strong reason for making this change. The block hash isn't all that useful. The only valid reason I can see is to find which fork you are on in the presence of long living forks, and that has obvious workarounds.

**Comment by ThomasArts** [comment]
Found this https://github.com/amiller/ethereum-blockhashes w.r.t. blockhash that is older.

I have no strong opinions about the 256, but would appreciate if we could change to the more logical idea of receiving the key-block hash of the current height in the next VM version.
