### ISSUE TITLE
I have two zombie processes on the node I created with docker. Is this normal?

### ISSUE THREAD

**Issue by bl-mds** [aeternity/aeternity#3124]

**Comment by tolbrino** [comment]
You need to be more specific and provide some OS information as well as information about running processes.

**Comment by tolbrino** [comment]
Closing since there is no further feedback. Feel free to open a new issue when more information is available.

**Comment by bl-mds** [comment]
Os:

**Comment by bl-mds** [comment]
Os:CentOS Linux release 7.7.1908 (Core)

**Comment by bl-mds** [comment]
Os:CentOS Linux release 7.7.1908 (Core)

**Comment by bl-mds** [comment]
Os:CentOS Linux release 7.7.1908 (Core)

**Comment by bl-mds** [comment]
Os:CentOS Linux release 7.7.1908 (Core)

#ps -aux |grep Z
1000      4362  0.0  0.0      0     0 ?        Zs   Jan19   0:00 [epmd] <defunct>
1000      4391  0.0  0.0      0     0 ?        Z    Jan19   0:00 [inet_gethost] <defunct>

**Comment by bl-mds** [comment]
Ubuntu has the same problem.

**Comment by tolbrino** [comment]
That process is the [Erlang Port Mapper Daemon](https://erlang.org/doc/man/epmd.html), which is a utility service for the Erlang Runtime System. If you stop the node, the `epmd` will continue to run since its essentially independent from a single instance of the ERTS. You are free to kill it yourself or keep it running, as it won't do anything on its own.

**Comment by bl-mds** [comment]
ok.
