### ISSUE TITLE
Migrate to latest possible stable OTP

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3293]
We are running OTP20. Since the release of OT23, OTP20 is no longer supported.

Investigate if OTP23 is possible, if not - migrate to OTP22

**Comment by uwiger** [comment]
Tests are already run on OTP 21, but we should take the chance to leave OTP 20 behind in the next hard fork.

BTW, not supporting OTP 20 will allow for some code cleanup, e.g. consistently using the new `try ... catch` syntax (re. stacktraces). Also, OTP 21 introduces useful things like `persistent_term`.

**Comment by velzevur** [comment]
I see this is a duplicate of #3104

**Comment by dincho** [comment]
> I see this is a duplicate of #3104

Then let's make this one to move to OTP 22 since the latest major is 23?

**Comment by radrow** [comment]
What is the argument for not jumping into 23?

**Comment by velzevur** [comment]
This had been updated to possibly go to 22 or 23. Currently expectation is that 21 should be stable but going to newer OTP versions might have issues with some dependencies.

This is a prerequisite for PR #3104 and they are not duplicates.

**Comment by michelboaventura** [comment]
I would like to help tackle this issue. Is there any easy start? I was thinking about migrating all the deps to work with OTP23. What do you think?

**Comment by uwiger** [comment]
### Progress as of 21 Aug 2020

Initial tests were made to build Aeternity using OTP 22.3 and OTP 23.0.2

Builds failed due to compiler warnings about deprecated functions. 
* [leveled](https://github.com/martinsumner/leveled) for using the now deprecated `gen_fsm`. The `rebar.config` in `leveled` already had instructions to ignore the warnings, but the `platform_define` checks didn't cover OTP versions later than 21. This has been fixed in the latest version, so updating the dependency is sufficient. This was properly done in [mnesia_leveled](https://github.com/aeternity/mnesia_leveled), and this was done in [PR #7](https://github.com/aeternity/mnesia_leveled/pull/7) (merged). This PR also fixed a compiler warning in the `mnesia_leveled` code.
* [jesse](https://github.com/for-GET/jesse) failed due to a similar reason (`http_uri:decode/1` deprecated). Again, the latest version handles this, and updating the dependency in the `aeternity ebar.config` addresses the build issue. However, there is a test dependency on [aestratum_client](https://github.com/aeternity/aestratum_client) which also depends on `jesse`, so it needed to be updated as well: see [PR #7](https://github.com/aeternity/aestratum_client/pull/7) (merged). The `aeternity rebar.config` of course needs to be updated to use the new version of `aestratum_client`.
* Compilation of `aesc_fsm.erl` failed in an internal consistency check using OTP 23.0.2. This was [fixed in OTP 23.0.3](https://bugs.erlang.org/browse/ERL-1333).


A very simplistic performance test was done, clocking the time it took to run the `aesc_fsm_SUITE`. Rough numbers (the numbers fluctuate between runs):
* OTP 20.3: 15 min 22 sec
* OTP 22.3: 12 min 46 sec
* OTP 23.0.3: 13 min 07 sec

The time difference between OTP 22 and 23 should be considered to be within the margin of error.

While updating things, [mnesia_rocksdb](https://github.com/aeternity/mnesia_rocksdb) should be brought up to a newer version of the [erlang-rocksdb](https://hex.pm/packages/rocksdb). The latest available version is 1.5.1, and `mnesia_rocksdb` uses 0.24.0. This is not strictly related to migrating to OTP 22 or 23, though.

**Comment by JayKickliter** [comment]
@michelboaventura 

PSA: I am not much of an erlang dev, but I do a lot of NIF work at my company. I found a lot of NIFs that broke with the EOL of the `erl_interface` library. So far I found that the universal solution is to remove `erl_interface` **AND** its replacement (`ei`) as dependencies of the NIF. In other words, almost every NIF module I see in the wild unnecessarily links to `erl_interface`/`ei`.
