### ISSUE TITLE
Whitelisting support scripts

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#3467]
Related to #3463, we need tools for easily selecting a preferred fork to sync from.

The hard-coded whitelists were effective in stopping the recent attacks, but the whitelist needs to be updated to have any effect against future attacks.

Suggestions:
* An aeternity extension script that creates a whitelist for the current fork and writes it to a specified file
* A configuration parameter to specify a whitelist file

**Comment by gorbak25** [comment]
The whitelist was a quick hack - the proper solution is to keep track of one hash which we consider "finalized" and reject blocks higher than the finalized one for which the predecessor is not the finalized block. Some caching would need to be done in order to avoid executing is_direct_predecesor every time we insert a block.

**Comment by uwiger** [comment]
I've been going back and forth on whether we should have a whitelist, or just a single hash. In the discussion of #3463, I suggested that a single hash will do. However, a sparse whitelist could serve as an optimization and a complement to the finalized hash. For example, when syncing, whitelisted hashes could be used to terminate quicker a sync against an unwanted fork.

But strictly speaking, I agree that a single hash might suffice.

**Comment by uwiger** [comment]
A whitelisting extension script was added as part of PR #3704
Closing
