### ISSUE TITLE
Which version to select!

### ISSUE THREAD

**Issue by Sandesh865** [aeternity/aeternity#3489]
Hey I want to run the latest node on my windows 10 using windows subsystem for linux (Ubuntu) when I open the setup-wsl which version should I choose I asks as follows  x.x.x

**Comment by velzevur** [comment]
@Sandesh865 as discussed on the forum already ([link](https://forum.aeternity.com/t/security-plan-for-increased-51-attack-resistances-of-the-aeternity-blockchain/8695/3)) WSL is no longer supported. We used to support till one year ago but it had been deprecated since. It could be the case the node is still running under WSL but there is no guarantee for it.
As always - you should use the latest and greatest version of the node, which at the moment is [5.7.0](https://github.com/aeternity/aeternity/tree/v5.7.0).
