### ISSUE TITLE
Never strip the init function from on-chain bytecode

### ISSUE THREAD

**Issue by gorbak25** [aeternity/aeternity#3510]
In order for the 
- https://github.com/aeternity/aesophia/issues/197
- https://github.com/aeternity/aesophia/issues/295

combo to be able to clone existing onchain contracts we need to keep the bytecode for the init function.
Right now when deploying onchain/offchain contracts we strip the init constructor to presumably save space(there are better ways to save space here). Cloning existing onchain contracts becomes infeasible using the above combo - one potential workaround would be to search for the initial contract create transaction to retrieve the original bytecode(with the init function still intact).

The Iris version of the Fate VM needs to keep the bytecode intact - as provided by the user in contract_create_tx. This also means that FateVM V2 will be unable to clone already existing contracts present in FateVM V1...

**Comment by marc0olo** [comment]
@hanssv what's the state of this? I thought that's already addressed 🤔

**Comment by marc0olo** [comment]
I found the issue because we had some discussion about bytecode verification today and I remembered that there was some issue with stripping the `init` function. cc @davidyuk

**Comment by ghallak** [comment]
I was looking into this today as I was trying to understand how `clone` is working without `init` function, but as I can see, this issue was relevant in `aevm` and `fate1` but is not relevant in `fate2`.

This [lines](https://github.com/aeternity/aeternity/blob/f55896feb63ec65e423a02f7082cac66b374b912/apps/aeprimop/src/aeprimop.erl#L1648-L1652) show that since `fate2` the `init` function is not being stripped.

Can this issue be closed?
