### ISSUE TITLE
cache invalidation for transaction endpoint doesn't seem to work as expected

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aeternity#3622]
sending the same request over and over doesn't invalidate the cache as would be expected, see attached video

https://www.youtube.com/watch?v=K94G3AcxCNc

**Comment by dincho** [comment]
The reason seems to be that the response ETAG does not include the transaction's block hash and it changes once it's included in a block and also during forks. Therefore wrong ETAG leads to wrong HTTP proxy revalidation of the requests.

So, the solution would be to include block hash in the ETAG as well.

**Comment by thepiwo** [comment]
@dincho is this something the core node api implementation has to change or the sdk?

**Comment by dincho** [comment]
The bug is is in the node, I'm addressing it right now
