### ISSUE TITLE
Make DryRunTxs a part of external API

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#3624]
In comparison with other debugging-related internal endpoints, the dry-run is heavily used in production primarily for static calls of smart contracts. From the side of JS SDK, this seems to be the one internal endpoint that is used in production, adding it to external API would allow improving user experience:
- by omitting internal URL in SDK initialization (and related questions about the reasoning of internal URL)
- simplifying running a fully-functional node because won't be needed to setup a reverse proxy in some cases (see #3616)
- simplify custom node setup for Superhero wallet and Base aepp (currently apps accepts only one URL that is used for both internal and external apis, so reverse proxy is required)

I understand the concerns about possible abusing of this endpoint, maybe its availability in external endpoints may be configurable in settings? (with a reasonable default value)

cc: @marc0olo @nikita-fuchs

**Comment by velzevur** [comment]
> I understand the concerns about possible abusing of this endpoint, maybe its availability in external endpoints may be configurable in settings? (with a reasonable default value)

I really hope so: this endpoint can potentially be computationally heavy and the API consumer does not pay for the computations being made. What is more, exposing this endpoint can be even dangerous for the node stability if the node is DDoSed via this particular endpoint. This endpoint was never intended to be used in production, that's why it lives under `debug`.

If this will be used in production, at least let's have the gas limit capped. I am preparing a new endpoint.

**Comment by marc0olo** [comment]
the problem is that currently this is the "standard-way" to perform following actions:
- calling "regular" (non-stateful) entrypoints
- determine the required fee for a contract call

I have never really understood why the "internal" or "debug" endpoint should live under a separate base-url. I guess this is just the case as this API is running on a separate port. by setting up a proxy (as it is the case for e.g. https://testnet.aeternity.io/) we don't need to keep the base-url separate.

what should be our recommendation / best practice here? as it is clear that `debug` endpoint shouldn't exposed to the public it's probably best to secure it. in this case we need to let the developer provide an authentication method to the SDK to authorize the usage of the `debug` endpoint.

again -> at the moment every developer jumping into the æcosystem and starting developing Sophia contracts is making heavy use of the `dry-run` endpoint

**Comment by velzevur** [comment]
The `internal` interface was intended to provide the node operator with some API regarding the node operation, so a proper client for interaction with the node can be developed accordingly. This idea never fully developed but we kept stuff like _do not use this in production_ there. That's why the `internal` interface is on a different port and it is bound to `127.0.0.1` by default. It was not meant to be exposed but we allowed it if the node operator really wants to.

This is OK for local development when the dev is the node operator but it sounds plain wrong if we expect wallets to be making gas cost estimates using internal debug endpoints of some publicly available nodes.

**Comment by marc0olo** [comment]
> This is OK for local development when the dev is the node operator but it sounds plain wrong if we expect wallets to be making gas cost estimates using internal debug endpoints of some publicly available nodes.

totally agree on that. I am just observing the status quo. to anybody, please correct me if I am wrong

**Comment by velzevur** [comment]
So I plan on exposing it to the external endpoint, adding a max gas limit. We should discuss also some authentication for those potentially computational heavy endpoints.

**Comment by thepiwo** [comment]
Generally I agree with the approach of the core team here. Dry-run is something only a minority of node operators want to expose and if so they should do so consciously as for the DDoS risks involved and additional load.

> I have never really understood why the "internal" or "debug" endpoint should live under a separate base-url

@marc0olo It's good for node operators to easily decide what to expose and what not to.

> So I plan on exposing it to the external endpoint, adding a max gas limit.

@velzevur I don't think this benefits anyone as then for higher gas limit calls we have to have a fallback to a non-limited node anyways.

Maybe it would be better to have an estimate gas endpoint, but I don't know if this is feasible
