### ISSUE TITLE
Broken bin/aeternity commands on macOS

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3789]
v6.* release bin/aeternity commands does not work as expected on recent macOS versions

for example `bin/aeternity daemon` does not return and respectively `bin/aeternity ping` incorrectly reports that the node is not running.

Looks like somehow related to https://github.com/erlware/relx/issues/862

**Comment by hanssv** [comment]
I think I see what goes wrong. But not why and how to fix it…

What happens when we build a prod-package is that our beloved `rebar3` (and internally `relx`) produces an ERTS environment that contains:
```
official> ls -l erts-10.7.2.13/bin
...
-r-xr-xr-x@ 1 hans  staff      887 Oct  1 15:02 erl
...
```
and that erl is just a small script containing:
```
#!/bin/sh
...
ROOTDIR="/usr/local/Cellar/erlang@22/22.3.4.21/lib/erlang"
BINDIR=$ROOTDIR/erts-10.7.2.13/bin
```
This is just wrong, we can’t expect that `ROOTDIR` to exist… (If it happens to exist the node commands work!) 

If I build a package locally it works - but this is because `ROOTDIR` then actually exists!!

If I remove `erts-10.7.2.13/bin/erl` then `bin/aeternity daemon` also works, but I suspect it then just reverts to something on my path, so this should be tested on a system without Erlang :sweat_smile:

A final observation, if I build a production package on my machine (with a self compiled OTP) `erts-…/bin/erl` is a binary - so it could also be an artefact of the brew installed OTP.

**Comment by tsloughter** [comment]
That `erl` should be a binary in the release, not a script. Maybe you are building with an old rebar3? It used to be the case it was a script before `dyn_erl` was used by `relx` to create the `erl` file (which is a binary).

**Comment by hanssv** [comment]
We are not building with an old `rebar3` - the problem turns out to be that step where `relx` copies `dyn_erl` over `erl` is allowed to silently fail (and it does in our case). `erl` is read-only when building on a `brew` installed Erlang OTP version.

**Comment by tsloughter** [comment]
Thanks for updating the issue. I can probably patch relx this week, am planning to release a new version soon so it would be for that.

My plan is that it'll attempt to change the permissions so it can overwrite `erl` with `dyn_erl`. If it is able to make the copy of erts that should always be possible since copying will change the ownership to the current user. But can you verify that is what you see in macos? That the `erl` file is read only but owned by your user so you can change it to read-write.

**Comment by hanssv** [comment]
@tsloughter confirmed; the copied `erl` is owned by the current user but read-only

**Comment by hanssv** [comment]
@tsloughter Any luck fixing this, I had a look over at `relx` but didn't see anything related?

**Comment by tsloughter** [comment]
@hanssv hey, sorry, I haven't gotten to it yet, forgot. I'll try to recall doing it this weekend.

**Comment by dincho** [comment]
Released in https://github.com/erlang/rebar3/releases/tag/3.19.0 however, it seems it does not support OTP 22

**Comment by dincho** [comment]
Fixed in https://github.com/aeternity/aeternity/pull/3991
